slnAmarantoGraciana/Models/Receta.cs
using SistemaWebMisRecetas.Validations;
using System.ComponentModel.DataAnnotations;

namespace SistemaWebMisRecetas.Models
{
    public class Receta
    {
        public int Id { get; set; }

        [Required]
        public string Titulo { get; set; }

        [Required]
        [CategoriaDesayuno]
        public string Categoria { get; set; }

        [Required]
        [DataType(DataType.MultilineText)]
        public string Ingredientes { get; set; }

        [Required]
        [DataType(DataType.MultilineText)]
        public string Instrucciones { get; set; }

        [Required]
        public string Nombre { get; set; }

        [Required]
        public string Apellido { get; set; }

        [Required]
        [EdadMayorQue]
        public int Edad { get; set; }

        [Required]
        [RegularExpression("^[^@]+@[^@]+\\.[a-zA-Z]{2,}$")]
        public string Email { get; set; }
    }
}

slnAmarantoGraciana/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;

namespace SistemaWebMisRecetas.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.Bienvenida = "Bienvenida a la página de sus recetas!";
            return View();
        }
    }
}

slnAmarantoGraciana/Controllers/RecetasController.cs
using System.Linq;

using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SistemaWebMisRecetas.Data;
using SistemaWebMisRecetas.Models;

namespace SistemaWebMisRecetas.Controllers
{
    public class RecetasController : Controller
    {
        private readonly RecetasContext context;

        public RecetasController(RecetasContext context)
        {
            this.context = context;
        }

        //todas las recetas
        public IActionResult Index()
        {
            var recetas = context.Recetas.ToList();
            return View("Index",recetas);
        }

        //crear una receta
        [HttpGet]
        public ActionResult Create()
        {
            Receta receta = new Receta();

            return View("Create", receta);//devolver al cliente html(vista)
        }

        //post: Opera/Create
        [HttpPost]
        public ActionResult Create(Receta receta)
        {
            if (ModelState.IsValid)
            {
                context.Recetas.Add(receta);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(receta);
        }

        //detalle de una receta
        [HttpGet]
        public ActionResult Details(string title)
        {
            var receta = (from i in context.Recetas
                          where title == i.Titulo
                          select i).FirstOrDefault();

            if (receta == null)
                return NotFound();
            else
                return View("Details", receta);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var receta = TraerUno(id);
            return View("Edit", receta);
        }

        [HttpPost]
        [ActionName("Edit")]
        public ActionResult EditConfirmed(Receta receta)
        {
            if (!ModelState.IsValid) return BadRequest();

            context.Entry(receta).State = EntityState.Modified;
            context.SaveChanges();

            return RedirectToAction("Index");
        }

        private Receta TraerUno(int id)
        {
            return context.Recetas.Find(id);
        }
    }
}

slnAmarantoGraciana/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}
<div class="maincontent">
    <header>
        Mis Recetas
    </header>

    <nav>
        <h2>Recetas</h2>
        @Html.ActionLink("Ver recetas","Index", "Recetas")

    </nav>

    <div class="parrafos">
        <p>
            <h1>Sobre el desayuno</h1>
            El desayuno es la primera comida que se consume en el día. El nombre deriva
            del hecho de que uno no come mientras duerme, por lo que al levantarse
            se encuentra en ayunas, rompiéndose ese ayuno al tomar esta comida.
        </p>

        <p>
            <h2>Su importancia</h2>
            El desayuno es la comida fundamental del día, ya que consumirlo o no,
            nos afecta de forma notable a corto y a largo plazo.
            Se ha demostrado que los niños que no desayunan o que solo toman un vaso de leche, rinden
            menos en el colegio que los que ingieren un desayuno adecuado.

            Estudios recientes afirman que el desayunar ayuda a acelerar el metabolismo,
            lo cual es un factor beneficioso para prevenir la obesidad.
        </p>
        <p>
            Nuestra especialidad, el desayuno americano, está compuesto por huevos, ya sean fritos o revueltos,
            bacon y tortitas americanas. Como bebida, suele optarse por el café o zumos de frutas y en ocasiones,
            en algunos hoteles y restaurantes se complementa con patatas fritas.
        </p>
    </div>

    @section SideBarOpcional{
        <div class="container">
            @ViewBag.Bienvenida
    
            <ul class="listaimagenes">
                <li>
                    <img src="~/css/img1.jpg"
                     width="200"
                     height="200">
                </li>
                <li>
                    <img src="~/css/img2.jpg"
                     width="200"
                     height="200">
                </li>
                <li>
                    <img src="~/css/img3.jpg"
                     width="200"
                     height="200">
                </li>
            </ul>
        </div>
  
     }
</div>

slnAmarantoGraciana/Views/Recetas/Create.cshtml
@model SistemaWebMisRecetas.Models.Receta

@{
    ViewData["Title"] = "Create";
}

<h1>Registrar una nueva receta</h1>
@using (Html.BeginForm("Create", "Recetas", FormMethod.Post))
{
    <p>
        @Html.LabelFor(model => model.Titulo)
        @Html.TextBoxFor(model => model.Titulo)
        @Html.ValidationMessageFor(model => model.Titulo)
    </p>
    <p>
        @Html.LabelFor(model => model.Categoria)
        @Html.TextBoxFor(model => model.Categoria)
        @Html.ValidationMessageFor(model => model.Categoria)
    </p>
    <p>
        @Html.LabelFor(model => model.Ingredientes)
        @Html.TextBoxFor(model => model.Ingredientes)
        @Html.ValidationMessageFor(model => model.Ingredientes)
    </p>
    <p>
        @Html.LabelFor(model => model.Instrucciones)
        @Html.TextBoxFor(model => model.Instrucciones)
        @Html.ValidationMessageFor(model => model.Instrucciones)
    </p>
     <p>
        @Html.LabelFor(model => model.Nombre)
        @Html.TextBoxFor(model => model.Nombre)
        @Html.ValidationMessageFor(model => model.Nombre)
      </p>
     <p>
        @Html.LabelFor(model => model.Apellido)
        @Html.TextBoxFor(model => model.Apellido)
        @Html.ValidationMessageFor(model => model.Apellido)
    </p>
    <p>
        @Html.LabelFor(model => model.Edad)
        @Html.TextBoxFor(model => model.Edad)
        @Html.ValidationMessageFor(model => model.Edad)
    </p>
    <p>
        @Html.LabelFor(model => model.Email)
        @Html.TextBoxFor(model => model.Email)
        @Html.ValidationMessageFor(model => model.Email)
    </p>
     
    <input type="submit" action="Create" />
    @Html.ActionLink("Volver al Index", "Index", "Recetas")
}
@section SideBarOpcional{
    <div class="container">
        <ul>
          
                <li>
                    @Html.ActionLink("Nueva receta", "Create", "Recetas")
                </li>
                <li>
                     @Html.ActionLink("Recetas", "Index", "Recetas")
                </li>
                <li>
                    @Html.ActionLink("Volver a Home", "Index", "Home")
                </li>
        </ul>
    </div>
            
    }

slnAmarantoGraciana/Views/Recetas/Details.cshtml
@model SistemaWebMisRecetas.Models.Receta

@{
    ViewData["Title"] = "Details";
}

 <h2>Detalle de la receta</h2>
    <p>
        @Html.DisplayNameFor(model => model.Titulo)
        @Html.DisplayFor(model => model.Titulo)
    </p>
    <p>
    @Html.DisplayNameFor(model => model.Categoria)
    @Html.DisplayFor(model => model.Categoria)
    </p>
    <p>
    @Html.DisplayNameFor(model => model.Ingredientes)
    @Html.DisplayFor(model => model.Ingredientes)
    </p>
    <p>
    @Html.DisplayNameFor(model => model.Instrucciones)
    @Html.DisplayFor(model => model.Instrucciones)
    </p>

@section SideBarOpcional{
    <div class="container">
            <ul>
                <li>
                    @Html.ActionLink("Nueva receta", "Create", "Recetas")
                </li>
                <li>
                     @Html.ActionLink("Recetas", "Index", "Recetas")
                </li>
                <li>
                    @Html.ActionLink("Volver a Home", "Index", "Home")
                </li>
            </ul>
    </div>
    }

slnAmarantoGraciana/Views/Recetas/Edit.cshtml
@{
    ViewData["Title"] = "Edit";
}

@model SistemaWebMisRecetas.Models.Receta

<h1>Editar Receta</h1>

@using (Html.BeginForm("Edit", "Recetas", FormMethod.Post))
{
    <div id="formulario">
        <div class="form-group">
            @Html.LabelFor(model => model.Titulo)
            @Html.TextBoxFor(model => model.Titulo)
            @Html.ValidationMessageFor(model => model.Titulo)
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Categoria)
            @Html.TextBoxFor(model => model.Categoria)
            @Html.ValidationMessageFor(model => model.Categoria)
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Instrucciones)
            @Html.TextBoxFor(model => model.Instrucciones)
            @Html.ValidationMessageFor(model => model.Instrucciones)
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ingredientes)
            @Html.TextBoxFor(model => model.Ingredientes)
            @Html.ValidationMessageFor(model => model.Ingredientes)
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre)
            @Html.TextBoxFor(model => model.Nombre )
            @Html.ValidationMessageFor(model => model.Nombre )
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellido )
            @Html.TextBoxFor(model => model.Apellido )
            @Html.ValidationMessageFor(model => model.Apellido )
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Edad )
            @Html.TextBoxFor(model => model.Edad )
            @Html.ValidationMessageFor(model => model.Edad )
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email )
            @Html.TextBoxFor(model => model.Email )
            @Html.ValidationMessageFor(model => model.Email )
        </div>

        <input type="submit"  value="Editar" action="" />
    </div>

    @section SideBarOpcional{
        <div class="container">
            <ul>
                <li>
                    @Html.ActionLink("Recetas", "Index", "Recetas")
                </li>
                <li>
                    @Html.ActionLink("Volver a Home", "Index", "Home")
                </li>
             </ul>
        </div>
    }
}

slnAmarantoGraciana/Views/Recetas/Index.cshtml
@model IEnumerable<SistemaWebMisRecetas.Models.Receta>


@{
    ViewData["Title"] = "Recetas";
}


    <table class="Receta">
        <tr>
        <th>@Html.DisplayNameFor(model => model.Id)</th>
            <th>@Html.DisplayNameFor(model => model.Titulo)</th>
            <th>@Html.DisplayNameFor(model => model.Categoria)</th>
            <th>@Html.DisplayNameFor(model => model.Ingredientes)</th>
            <th>@Html.DisplayNameFor(model => model.Instrucciones)</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
                <td>
                    @Html.ActionLink($"{item.Titulo}", "Details", "Recetas", new {title = item.Titulo})
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Categoria)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ingredientes)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Instrucciones)
                </td>
            </tr>
        }
    </table>

    <table class="Autor" >
        <tr>
            <th>@Html.DisplayNameFor(model => model.Nombre)</th>
            <th>@Html.DisplayNameFor(model => model.Apellido)</th>
            <th>@Html.DisplayNameFor(model => model.Edad)</th>
            <th>@Html.DisplayNameFor(model => model.Email)</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Apellido)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Edad)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.ActionLink("Editar", "Edit", "Recetas", new {id = item.Id})
                </td>
            </tr>
        }
    </table>


@section SideBarOpcional{
        <div class="container">
            <ul>
                <li>
                    @Html.ActionLink("Nueva receta", "Create", "Recetas")
                </li>
                <li>
                    @Html.ActionLink("Volver a Home", "Index", "Home")
                </li>
            </ul>
        </div>
    }

slnAmarantoGraciana/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - slnAmarantoGraciana</title>
    <link href="~/css/main.css" rel="stylesheet" type="text/css" />
    </head>
<body>
    
    <section>
        <main>
            @RenderBody()
        </main>
    </section>

    <aside id="sidebar">
        @RenderSection("SideBarOpcional", required : false)
    </aside>


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - slnAmarantoGraciana - graciana_amaranto@hotmail.com
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>